# Generated by Django 5.0.2 on 2025-10-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0001_initial'),
    ]

    operations = [
    ]
