# Generated by Django 5.0.2 on 2025-10-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_alumnos_maestros'),
    ]

    operations = [
    ]
