# Generated by Django 5.0.2 on 2025-10-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0005_auto_20251017_1222'),
    ]

    operations = [
    ]
