# Generated by Django 5.0.2 on 2025-10-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0007_auto_20251017_1838'),
    ]

    operations = [
    ]
