# Generated by Django 5.0.2 on 2025-10-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0008_auto_20251018_1118'),
    ]

    operations = [
    ]
