# Generated by Django 5.0.2 on 2025-10-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0010_auto_20251019_1153'),
    ]

    operations = [
    ]
