# Generated by Django 5.0.2 on 2025-10-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0011_auto_20251019_1201'),
    ]

    operations = [
    ]
