# Generated by Django 5.0.2 on 2025-10-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0012_auto_20251019_1220'),
    ]

    operations = [
    ]
