# Generated by Django 5.0.2 on 2025-10-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0013_auto_20251023_0603'),
    ]

    operations = [
    ]
