# Generated by Django 5.0.2 on 2025-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0014_auto_20251023_2135'),
    ]

    operations = [
    ]
