# Generated by Django 5.0.2 on 2025-11-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0015_alter_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
    ]
