# Generated by Django 5.0.2 on 2025-11-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0016_auto_20251117_1924'),
    ]

    operations = [
    ]
