# Generated by Django 5.0.2 on 2025-11-24 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0017_auto_20251123_2128'),
    ]

    operations = [
    ]
