# Generated by Django 5.0.2 on 2025-12-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0018_auto_20251123_2140'),
    ]

    operations = [
    ]
