# Generated by Django 5.0.2 on 2025-12-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0019_auto_20251130_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreEvento', models.CharField(max_length=255)),
                ('tipoEvento', models.CharField(max_length=255)),
                ('fechaRealizacion', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_json', models.TextField()),
                ('progEducativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsableEvento', models.IntegerField()),
                ('nombreResponsable', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupoEvento', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
