# Generated by Django 5.0.2 on 2025-12-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0020_eventos_alter_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horaFin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='horaInicio',
            field=models.CharField(max_length=255),
        ),
    ]
